"""Subclass of MyFrame1, which is generated by wxFormBuilder."""

import wx
import test

# Implementing MyFrame1
class MyProject1MyFrame1( test.MyFrame1 ):
	def __init__( self, parent ):
		test.MyFrame1.__init__( self, parent )

	# Handlers for MyFrame1 events.
	def txt1( self, event ):
		# TODO: Implement txt1
		self.m_staticText2.SetLabel('Hello wxPython!!')
		

	def txt2( self, event ):
		# TODO: Implement txt2
		self.m_staticText3.SetLabel('Goodbye wxPython!!')

	def paint( self, event ):
		# TODO: Implement paint
		pass


