"""Subclass of グラフ, which is generated by wxFormBuilder."""

import wx
import グラフ
import matplotlib.pyplot as plt
import math 
import numpy as np

# Implementing グラフ
class グラフグラフ( グラフ.グラフ ):
	def __init__( self, parent ):
		グラフ.グラフ.__init__( self, parent )

	# Handlers for グラフ events.
	def render( self, event ):
		# TODO: Implement render
		a=int(self.m_textCtrl1.GetValue())
		
		
		x_a=[]
		y_a=[]
		

		for x in np.arange(-20,20,0.01):
			y=a/(a**2+x**2)

			x_a.append(x)
			y_a.append(y)

		plt.plot(x_a, y_a, color="k") # 点列(x,y)を黒線で繋いだプロット
		plt.show() # プロットを表示

	def deg( self, event ):
		# TODO: Implement deg
		pass


