"""Subclass of グラフ, which is generated by wxFormBuilder."""

import wx
import グラフ

# Implementing グラフ
class グラフグラフ( グラフ.グラフ ):
	def __init__( self, parent ):
		グラフ.グラフ.__init__( self, parent )

	# Handlers for グラフ events.
	def render( self, event ):
		# TODO: Implement render
		pass

	def deg( self, event ):
		# TODO: Implement deg
		pass


